### ISSUE TITLE
EADDRINUSE error

### ISSUE THREAD

**Issue by alexsmith1665** [lspiehler/node-fauxmo#4]
Hello, I am getting the following error when I try to run "node index.js"

/home/pi/MagicMirror/node_modules/node-fauxmo/src/SSDPService.js:104
                throw err;
                ^

Error: bind EADDRINUSE 0.0.0.0:1900
    at state.handle.lookup (dgram.js:242:18)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

I see in your instructions that I need to find what device is listening on port 1900, but I'm not sure how to do that. Could you tell me how to figure that out? I have successfully run the command before with no issues. I have not added any new devices since then.

edit: I pasted the wrong error message, so I updated it to the correct one.

**Comment by alexsmith1665** [comment]
Is this module still maintained?
